import {readFileSync, writeFileSync} from 'node:fs';
import {join, dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

export const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export function parseVersion(value) {
  const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-rc\.(0|[1-9]\d*))?$/.exec(value);
  if (!match) throw Error('版本必须为 major.minor.patch 或 major.minor.patch-rc.N');
  const parts = match.slice(1).map(v => v === undefined ? Infinity : Number(v));
  if (parts.slice(0, 3).some(v => v > 65535) || (match[4] !== undefined && !Number.isSafeInteger(parts[3]))) throw Error('版本数值过大');
  return parts;
}
export function compareVersions(left, right) {
  const a = parseVersion(left), b = parseVersion(right);
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return a[i] > b[i] ? 1 : -1;
  return 0;
}
export function readVersion(directory = root) {
  const value = JSON.parse(readFileSync(join(directory, 'version.json'), 'utf8'));
  parseVersion(value.version);
  if (!Number.isSafeInteger(value.androidVersionCode) || value.androidVersionCode < 1 || value.androidVersionCode > 2100000000) {
    throw Error('androidVersionCode 必须为 1 至 2100000000 的整数');
  }
  return value;
}

// Files required by platform tooling remain checked in; version.json is their only authority.
export function versionFiles(directory, value = readVersion(directory)) {
  const changes = new Map();
  const edit = (path, update) => {
    const source = readFileSync(join(directory, path), 'utf8');
    changes.set(path, update(source));
  };
  const replace = (path, pattern, replacement) => edit(path, source => {
    if (!pattern.test(source)) throw Error(`无法定位版本字段：${path}`);
    return source.replace(pattern, replacement);
  });
  for (const path of ['desktop/package.json', 'desktop/src-tauri/tauri.conf.json']) {
    replace(path, /("version"\s*:\s*")[^"]+"/, `$1${value.version}"`);
  }
  edit('desktop/package-lock.json', source => {
    const json = JSON.parse(source);
    json.version = value.version; json.packages[''].version = value.version;
    return JSON.stringify(json, null, 2) + '\n';
  });
  replace('desktop/src-tauri/Cargo.toml', /(\[package\][\s\S]*?^version\s*=\s*")[^"]+"/m, `$1${value.version}"`);
  replace('desktop/src-tauri/Cargo.lock', /(name = "nas-find-desktop"\r?\nversion = ")[^"]+"/, `$1${value.version}"`);
  edit('android/app/build.gradle.kts', source => {
    if (!/versionCode = \d+/.test(source) || !/versionName = "[^"]+"/.test(source)) throw Error('无法定位 Android 版本字段');
    return source.replace(/versionCode = \d+/, `versionCode = ${value.androidVersionCode}`)
      .replace(/versionName = "[^"]+"/, `versionName = "${value.version}"`);
  });
  changes.set('nasfind/_version.py', `# Generated by node scripts/version.mjs sync; edit version.json.\n__version__ = "${value.version}"\n`);
  return changes;
}
export function syncVersions(directory = root, value = readVersion(directory)) {
  const changes = versionFiles(directory, value); // Read and validate all inputs before writing.
  for (const [path, text] of changes) writeFileSync(join(directory, path), text);
}
export function validateVersions(directory = root, tag = '') {
  const value = readVersion(directory);
  if (tag && tag !== `v${value.version}`) throw Error(`标签 ${tag} 与产品版本 v${value.version} 不一致`);
  for (const [path, expected] of versionFiles(directory, value)) {
    // Ignore newline conventions, but catch mismatched platform/lock versions and generated content.
    const actual = readFileSync(join(directory, path), 'utf8').replaceAll('\r\n', '\n');
    if (actual !== expected.replaceAll('\r\n', '\n')) throw Error(`${path} 与 version.json 不一致，请运行 node scripts/version.mjs sync`);
  }
  return value;
}
export function bumpVersion(directory, version) {
  const previous = readVersion(directory);
  if (compareVersions(version, previous.version) <= 0) throw Error('新版本必须高于当前版本');
  const next = {...previous, version, androidVersionCode: previous.androidVersionCode + 1};
  if (next.androidVersionCode > 2100000000) throw Error('Android 版本序号超出上限');
  syncVersions(directory, next);
  writeFileSync(join(directory, 'version.json'), JSON.stringify(next, null, 2) + '\n');
  return next;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  switch (process.argv[2]) {
    case 'sync': syncVersions(); break;
    case 'check': validateVersions(); break;
    case 'bump': bumpVersion(root, process.argv[3]); break;
    default: throw Error('Usage: node scripts/version.mjs sync|check|bump <version>');
  }
  console.log(readVersion());
}
